app:
  name: Furballs
  description: ${app.name} manages animal tracking needs for Animal Shelters

server:
  port: 8080

spring:
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    # jdbc:postgresql://host:port/database?properties
    url: jdbc:postgresql://localhost:5433/main
    username: postgres
    password: admin
    hikari:
      schema: shelter

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
      show-sql: true
    main:
      web-development-type: servlet